### ISSUE TITLE
Filter Navbar

### ISSUE THREAD

**Issue by mrkc2303** [mrkc2303/Takeaway#25]
Make a filter nav bar with 6 buttons: Filters, Ratings, Safe and Hygiene, Pure Veg, Delivery Time & Great Offers

Make proper buttons with text and logo.

THANKS

**Comment by yellowberard** [comment]
![image](https://user-images.githubusercontent.com/82977727/133655279-9bb21474-b940-4e10-89b9-37e79017c246.png)

Sample

**Comment by yellowberard** [comment]
![image](https://user-images.githubusercontent.com/82977727/133655411-a8fed86e-a165-4c4b-bd65-abcfa4b49b23.png)
sample-2
